Repository Likelion-Project-3/yeondu-market, pull requests merged in 2022-07, with the labels that each got.

#13 #11 - Feat:빈 피드 화면 페이지
  src/pages/HomePage.css
  src/pages/HomePage.jsx
Labels: CSS, React

#17 #16 - Feat: 검색 컴포넌트 개발
  src/components/feed/TopSearchNav.css
  src/components/feed/TopSearchNav.jsx
Labels: CSS, React, component

#20 #15 - Feat:사용자 프로필 생성
  src/App.jsx
  src/assets/basic-profile-img.svg
  src/assets/icon/icon-message-circle2.svg
  src/assets/icon/icon-share.svg
  src/components/profile/MyProfile.css
  src/components/profile/MyProfile.jsx
Labels: CSS, component

#22 #21 - Feat: 좋아요 버튼 컴포넌트 개발
  src/assets/icon/icon-heart-green.svg
  src/assets/icon/icon-heart.png
  src/assets/icon/icon-heart.svg
  src/components/Like.css
  src/components/Like.jsx
Labels: CSS, React, component

#27 #26 - Style: css 컬러 변수 추가, png파일 -> svg로 교체
  src/assets/icon/icon-edit.png
  src/assets/icon/icon-heart-active.png
  src/assets/icon/icon-home-fill.png
  src/assets/icon/icon-home-fill.svg
  src/assets/icon/icon-home.png
  src/assets/icon/icon-message-circle-fill.png
  src/assets/icon/icon-message-circle.png
  src/assets/icon/icon-search.svg
  src/assets/icon/icon-user-fill.png
  src/assets/icon/icon-user.png
  src/components/TapMenu.css
  src/components/TopBasicNav.css
  src/components/chat/ChatComment.css
  src/components/chat/ChatItem.css
  src/components/feed/TopSearchNav.css
  src/components/modal/modalAlert.css
  src/components/modal/profileModal.css
  src/components/profile/MyProfile.css
  src/pages/HomePage.css
  src/pages/chat/ChatRoomPage.css
  src/reset.css
Labels: CSS

#28 #24 - Style: 게시글 작성 페이지 CSS 변수 적용
  src/pages/feed/UploadPost.css
Labels: CSS

#30 #25 - Feat:상품 등록 컴포넌트 개발
  src/App.jsx
  src/components/uploads/ProductUpload.css
  src/components/uploads/ProductUpload.jsx
Labels: CSS, component

#46 Feat/#1/splash화면
  src/components/Splash.css
  src/components/Splash.jsx
Labels: CSS, React, component

#48 #47-Feat:이메일로그인과 회원가입 개발
  src/components/Join.css
  src/components/Join.jsx
  src/components/LoginButton.css
  src/components/LoginButton.jsx
Labels: CSS, React, component

#58 #57 - Style: 태그변경으로인한css수정
  src/components/TapMenu.css
  src/components/TapMenu.jsx
Labels: CSS

#51 #49-Feat:로그인 화면 합쳐집니다
  src/pages/LoginEmail.css
  src/pages/LoginEmail.jsx
Labels: CSS, React, component

#60 #59-Design : follow classname변경
  src/components/follow/FollowHeader.jsx
  src/components/follow/FollowingHeader.jsx
  src/pages/feed/FollowerList.css
Labels: CSS

#56 #42 - Feat: 프로필 설정 페이지 개발
  src/assets/upload-file.svg
  src/components/ProfileForm.css
  src/components/ProfileForm.jsx
  src/pages/ProfileSettingPage.css
  src/pages/ProfileSettingPage.jsx
Labels: question, CSS, React, component

#52 #50-Feat:회원가입개발 합쳐집니다
  src/pages/Joinmembership.jsx
Labels: CSS, React, component

#66 #65 - Refactor: 기본 프로필 이미지 컴포넌트화
  src/components/BasicProfileImg.css
  src/components/BasicProfileImg.jsx
  src/components/ProfileForm.jsx
  src/components/feed/Post.css
  src/components/feed/Post.jsx
  src/components/feed/PostComment.css
  src/components/feed/PostComment.jsx
  src/components/profile/ProfileInfo.css
  src/components/profile/ProfileInfo.jsx
  src/pages/ProfileSettingPage.css
  src/pages/ProfileSettingPage.jsx
Labels: React, component

#70 Feat/#69/상품등록컴포넌트
  src/assets/product-img.svg
  src/components/product/ProductCard.css
  src/components/product/ProductCard.jsx
  src/components/product/ProductContainer.css
  src/components/product/ProductContainer.jsx
  src/components/profile/MyProfileBtn.css
  src/components/profile/MyProfileBtn.jsx
  src/components/profile/ProfileInfo.css
  src/components/profile/UserProfileBtn.css
  src/components/profile/UserProfileBtn.jsx
  src/pages/feed/MyProfile.css
  src/pages/feed/MyProfile.jsx
  src/pages/feed/Profile.css
Labels: CSS, component

#73 #62 - Feat: EditProfile, Search 페이지 생성
  src/pages/EditProfile.css
  src/pages/EditProfile.jsx
  src/pages/feed/Search.css
  src/pages/feed/Search.jsx
Labels: CSS, React

#77 #68 - Rename: 채팅관련 파일명 변경
  src/App.jsx
  src/components/chat/ChatItem.css
  src/components/chat/ChatItem.jsx
  src/components/chat/TopChatNav.jsx
  src/pages/chat/ChatList.css
  src/pages/chat/ChatList.jsx
  src/pages/chat/ChatRoom.css
  src/pages/chat/ChatRoom.jsx
Labels: enhancement, React, Rename

#76 #74-Feat:setTimeout을 이용하여 Splsh 화면에서 로그인화면으로 변경
  src/components/Splash.jsx
Labels: enhancement, React

#78 #75 - Refactor: 파일 업로드 버튼 컴포넌트화 및 사용 파일 변경
  src/components/UploadFileBtn.css
  src/components/UploadFileBtn.jsx
  src/components/chat/ChatComment.css
  src/components/chat/ChatComment.jsx
  src/components/profile/ProfileForm.css
  src/components/profile/ProfileForm.jsx
  src/pages/SetProfile.css
  src/pages/SetProfile.jsx
  src/pages/feed/ProductUpload.css
  src/pages/feed/ProductUpload.jsx
  src/pages/feed/UploadPost.css
  src/pages/feed/UploadPost.jsx
Labels: React, component

#72 #39-Feat:splash 화면에서 로그인화면으로 변경
  src/pages/intro.css
  src/pages/intro.jsx
Labels: CSS, React

#83 #79 - Feat: 게시글 텍스트 업로드
  src/components/button/UploadFileBtn.jsx
  src/pages/UploadPost.jsx
  src/pages/style/UploadPost.css
Labels: React, API

#86 #84 - Feat:axios를 사용하여 내프로필정보를 불러왔습니다
  src/components/profile/ProfileInfo.jsx
  src/pages/MyProfile.jsx
Labels: React, API

#93 #85 - Feat: 이미지 post 요청 기능
  src/pages/UploadPost.jsx
Labels: React, API

#96 #94 - Feat: 이미지 미리보기 기능
  src/pages/UploadPost.jsx
  src/pages/style/UploadPost.css
Labels: CSS, React

#100 #89 - Feat:프로필에서 내가 쓴 글 리스트
  src/components/post/Like.jsx
  src/components/post/PostItem.css
  src/components/post/PostItem.jsx
  src/components/post/PostList.jsx
  src/pages/MyProfile.jsx
Labels: React, API

#101 #91 - Feat: 회원가입 Join 페이지 기능 구현
  src/App.jsx
  src/components/loginjoin/IdPwForm.css
  src/pages/Join.jsx
Labels: React, API

#102 #99 - Feat: 게시글 삭제 기능
  src/components/modal/PostAlert.jsx
  src/components/modal/PostModal.jsx
Labels: React, API

#104 #95 - Feat: 회원가입-SetProfile 유효성 검사 기능
  src/components/profile/ProfileForm.jsx
Labels: React, API

#90 #88 - Feat:상품등록 페이지 연결 + api 연결(미완) + 유효성검사(미완)
  src/App.jsx
  src/components/post/PostItem.jsx
  src/components/profile/MyProfileBtn.jsx
  src/pages/MyProfile.jsx
  src/pages/UploadProduct.jsx
  src/pages/style/UploadProduct.css
Labels: React, API

#97 #84-Refactor:상단 메뉴바 컴포넌트
  src/components/chat/TopChatNav.css
  src/components/chat/TopChatNav.jsx
  src/components/common/TopBasicNav.css
  src/components/common/TopBasicNav.jsx
  src/components/common/TopMenuComponent.css
  src/components/common/TopMenuComponent.jsx
  src/components/follow/FollowHeader.jsx
  src/components/follow/FollowingHeader.jsx
  src/components/search/TopSearchNav.css
  src/components/search/TopSearchNav.jsx
  src/pages/EditProfile.jsx
  src/pages/UploadPost.jsx
  src/pages/UploadProduct.jsx
  src/pages/style/FollowerList.css
  src/pages/style/UploadPost.css
  src/pages/style/UploadProduct.css
Labels: CSS, React, component

#108 #107 - Feat:프로필에 상품리스트 설정
  src/components/post/PostList.jsx
  src/components/product/ProductCard.jsx
  src/components/product/ProductContainer.css
  src/components/product/ProductContainer.jsx
  src/pages/MyProfile.jsx
Labels: React, component

#113 #111 - Feat: 게시글 상세 페이지
  src/App.jsx
  src/components/comment/PostCommentInput.jsx
  src/components/modal/PostAlert.jsx
  src/components/post/PostItem.css
  src/components/post/PostItem.jsx
  src/pages/EditPost.jsx
  src/pages/Post.jsx
  src/pages/UploadPost.jsx
  src/pages/UploadProduct.jsx
Labels: CSS, React, API, component

#117 #110 - Feat: 게시글 신고 기능
  src/App.jsx
  src/components/modal/ReportPostModal.jsx
  src/components/modal/profileModal.css
  src/pages/EditPost.jsx
  src/pages/Post.jsx
Labels: React, API, component

#116 #105 - Feat: 프로필 이미지 등록 기능
  src/components/common/BasicProfileImg.jsx
  src/components/profile/ProfileForm.jsx
Labels: React, API

#119 #98 - Feat:점버튼을 누르면 로그아웃 모달로 연결
  src/components/common/TopBasicNav.jsx
Labels: React

#125 #124 - Feat: 활성화 시 아이콘 색 변경
  src/assets/icon/icon-home-fill.svg
  src/assets/icon/icon-message-circle-fill.svg
  src/assets/icon/icon-user-fill.svg
  src/components/common/TapMenu.css
  src/components/common/TapMenu.jsx
Labels: CSS, React

#127 #126 - Feat:앨범형 게시글
  src/components/post/PostAlbum.css
  src/components/post/PostAlbum.jsx
  src/components/post/PostAlbumItem.css
  src/components/post/PostAlbumItem.jsx
  src/pages/MyProfile.jsx
  src/pages/style/MyProfile.css
Labels: component

#121 #120 - Feat:채팅방에서 채팅방나가기를 모달로 연결
  src/components/chat/TopChatNav.jsx
Labels: React

#130 #122 - Feat:댓글자의 점 버튼을 눌러 신고하기를 모달로 연결
  src/components/comment/PostComment.jsx
  src/components/modal/CommentModal.jsx
Labels: React, component

#128 #123 - Feat: 업로드 버튼 활성화
  src/pages/EditPost.jsx
  src/pages/UploadPost.jsx
Labels: CSS, React

#132 #131 - Fix:프로필 오류 수정
  src/components/profile/ProfileInfo.jsx
  src/pages/MyProfile.jsx
Labels: bug, React

#134 #115 - Feat:상품모달연결
  src/components/modal/Alert.css
  src/components/modal/Modal.css
  src/components/modal/ProductAlert.jsx
  src/components/modal/ProductModal.jsx
  src/components/post/PostAlbum.jsx
  src/components/post/PostItem.jsx
  src/components/product/ProductCard.css
  src/components/product/ProductCard.jsx
  src/components/product/ProductContainer.jsx
  src/pages/MyProfile.jsx
Labels: React, component

#136 #135 - Feat:팔로우,팔로잉페이지 연결
  src/App.jsx
  src/components/product/ProductContainer.jsx
  src/components/profile/ProfileInfo.jsx
  src/pages/FollowerList.jsx
  src/pages/FollowingList.jsx
Labels: component

#140 #137 - Feat:상품 삭제 기능
  src/components/modal/ProductAlert.jsx
Labels: React, API, component

#141 #129 - Feat: 이미지 삭제 기능
  src/assets/icon/close.svg
  src/pages/UploadPost.jsx
  src/pages/style/UploadPost.css
Labels: CSS, React

#142 #118 - Feat: 회원가입 완성
  src/App.jsx
  src/components/profile/ProfileForm.jsx
  src/pages/Join.jsx
  src/pages/Register.jsx
  src/pages/SetProfile.jsx
  src/pages/style/SetProfile.css
Labels: React, API

#145 #144 - Style: 코드 정리
  src/pages/Login.jsx
Labels: React

#149 #147 - Fix: 이미지 경로 수정
  src/components/post/PostItem.jsx
  src/pages/EditPost.jsx
  src/pages/UploadPost.jsx
Labels: bug, React, API

#153 #152 - Fix: /home으로 이동
  src/pages/Login.jsx
Labels: bug

#154 #148 - Feat:상품의 가격을 천단위마다 콤마
  src/components/product/ProductCard.jsx
  src/pages/UploadProduct.jsx
Labels: React, component

#155 #150 - Feat: 게시글 상세 페이지
  src/components/comment/PostComment.css
  src/components/post/PostItem.css
  src/components/post/PostItem.jsx
  src/pages/Post.jsx
  src/pages/style/Post.css
Labels: CSS, React, component

#158 #151 - Fix:상품 이미지 경로 수정
  src/components/product/ProductCard.jsx
  src/pages/MyProfile.jsx
  src/pages/UploadProduct.jsx
Labels: bug, React

#159 #156 - Fix:앨범형 게시글 리스트 이미지 경로 수정
  src/components/post/PostAlbum.css
  src/components/post/PostAlbumItem.jsx
Labels: bug, React

#161 #160 - Feat:프로필페이지에서 TapMenu css 변경
  src/components/post/PostAlbum.css
  src/components/post/PostList.jsx
  src/components/post/postList.css
Labels: CSS

#162 #157 - Feat:앨범형 게시글 리스트 상세페이지 연결
  src/components/post/PostAlbumItem.css
  src/components/post/PostAlbumItem.jsx
Labels: React

#164 #163 - Feat: 게시글 관련파일 IR 추가
  src/components/comment/PostComment.jsx
  src/components/comment/PostCommentInput.jsx
  src/components/post/Like.jsx
  src/components/post/PostItem.jsx
  src/pages/EditPost.jsx
  src/pages/Post.jsx
  src/pages/UploadPost.jsx
Labels: enhancement

#165 #143 - Feat: 프로필 수정 기능
  src/App.jsx
  src/components/common/TopMenuComponent.css
  src/components/common/TopMenuComponent.jsx
  src/components/profile/MyProfileBtn.jsx
  src/components/profile/ProfileForm.css
  src/components/profile/ProfileForm.jsx
  src/pages/EditProfile.jsx
  src/pages/SetProfile.jsx
Labels: React, API

#169 #133 - Feat:로그아웃 여부 Alert 연결
  src/components/common/TopBasicNav.css
  src/components/common/TopBasicNav.jsx
  src/components/modal/Modal.css
  src/components/modal/ProfileModal.jsx
Labels: CSS, React, component

#172 #170 - Design:모달 스타일 변경
  src/components/chat/LeaveChatModal.css
  src/components/chat/LeaveChatModal.jsx
  src/components/chat/TopChatNav.jsx
  src/components/common/TopMenuComponent.css
Labels: CSS

#174 #171 - Feat: 토큰 유무에 따른 자동로그인 기능 추가
  src/App.jsx
Labels: React

#180 #179 - Fix: 회원가입 완료 시 로그인 페이지로 이동 및 버튼 수정
  src/components/profile/ProfileForm.jsx
  src/pages/SetProfile.jsx
Labels: bug

#181 #177 - Feat:상품등록 버튼 disabled + 프로필 정보없을실 null
  src/components/post/PostAlbum.jsx
  src/components/post/PostList.jsx
  src/components/product/ProductContainer.jsx
  src/pages/UploadProduct.jsx
Labels: CSS, React, component

#182 #178 - Feat: 복수 이미지 게시글 아이템
  src/components/post/PostItem.css
Labels: CSS

#184 #183 - Feat: 게시글 작성일 포맷팅
  src/components/post/PostItem.jsx
Labels: React, component

#190 #189 - Feat: 작성자 프로필 이미지
  src/components/comment/PostCommentInput.jsx
  src/pages/EditPost.jsx
  src/pages/UploadPost.jsx
Labels: React, API, component

#193 #146 - Feat: 게시글 이미지 수정
  src/pages/EditPost.jsx
Labels: React, API

#195 #192 - Feat:token없을시 로그인창으로 이동
  src/pages/Home.jsx
  src/pages/MyProfile.jsx
Labels: React

#185 #173 - Feat:게시글 수정 및 삭제 모달 연결
  src/components/modal/Modal.css
  src/components/modal/PostAlert.jsx
  src/components/modal/PostModal.jsx
  src/components/post/PostItem.jsx
Labels: CSS, React, component

#197 #196 - 팔로잉 리스트 api 연결
  src/components/follow/FollowingCard.jsx
  src/components/follow/FollowingContainer.jsx
  src/components/profile/ProfileInfo.jsx
  src/pages/FollowingList.jsx
Labels: React, API, component

#200 #198 - 팔로우리스트 api 연결
  src/components/common/TapMenu.jsx
  src/components/follow/FollowerCard.jsx
  src/components/follow/FollowerContainer.jsx
  src/pages/FollowerList.jsx
Labels: React, API, component

#199 #175 - Fix: 프로필 이미지 수정 가능
  src/components/profile/ProfileForm.jsx
  src/pages/EditProfile.jsx
  src/pages/SetProfile.jsx
Labels: bug, React

#203 #194 - Feat: 게시글 댓글 작성 기능
  src/components/comment/PostComment.css
  src/components/comment/PostComment.jsx
  src/components/comment/PostCommentInput.jsx
  src/pages/Post.jsx
Labels: React, API, component

#202 #201 - 유저 프로필 연결
  src/App.jsx
  src/components/follow/FollowingCard.jsx
  src/components/post/PostItem.jsx
  src/components/profile/ProfileBtn.jsx
  src/components/profile/ProfileInfo.jsx
  src/components/profile/UserProfileBtn.css
  src/pages/MyProfile.jsx
Labels: React, component

#206 #205 - 게시글 삭제 alert 연결
  src/components/modal/PostAlert.jsx
  src/components/modal/PostModal.jsx
  src/components/post/PostItem.jsx
Labels: React, component

#207 #204 - Fix: 게시글 모달 기능 수정
  src/components/modal/PostAlert.jsx
  src/components/modal/PostModal.jsx
  src/components/post/PostItem.css
  src/components/post/PostItem.jsx
Labels: React, API, component

#209 #208 - Rename: 핸들러명 통일
  src/components/comment/PostCommentInput.jsx
  src/components/modal/PostAlert.jsx
  src/components/modal/PostModal.jsx
  src/components/post/PostItem.jsx
  src/pages/EditPost.jsx
  src/pages/Post.jsx
  src/pages/UploadPost.jsx
Labels: React, Rename

#213 Design/#212/경고문구색상
  src/App.jsx
  src/components/loginjoin/IdPwForm.css
  src/components/profile/ProfileForm.css
  src/pages/style/Home.css
Labels: CSS

#215 #214 - Fix: 수정 페이지 유저 프로필 불러오기
  src/pages/EditPost.jsx
Labels: React, API

#216 #191 - Feat: 검색 기능
  src/components/common/TopMenuComponent.css
  src/components/common/TopMenuComponent.jsx
  src/components/search/TopSearchNav.css
  src/components/search/TopSearchNav.jsx
  src/components/search/UserList.css
  src/components/search/UserList.jsx
  src/pages/Home.jsx
  src/pages/Search.jsx
  src/pages/style/Search.css
Labels: React, API, component

#219 #211 - Feat: 댓글 삭제 신고 기능
  src/components/comment/PostComment.jsx
  src/components/modal/CommentModal.jsx
  src/components/modal/Modal.css
  src/pages/Post.jsx
Labels: React, API, component

#218 #217 - 팔로우, 언팔로우 api연결
  src/components/profile/ProfileInfo.jsx
  src/components/profile/UserProfileBtn.css
  src/components/profile/UserProfileBtn.jsx
  src/pages/FollowerList.jsx
  src/pages/FollowingList.jsx
Labels: React, API, component

#222 #220 - 팔로잉, 팔로우 정보 리스트 불러오기
  src/App.jsx
  src/components/product/ProductContainer.jsx
  src/components/profile/ProfileInfo.jsx
  src/pages/FollowerList.jsx
  src/pages/FollowingList.jsx
  src/pages/MyProfile.jsx
Labels: React, component

#224 #223 - Feat: 404 페이지 라우팅
  src/App.jsx
  src/assets/icon/404.svg
  src/pages/NotFound.jsx
  src/pages/style/NotFound.css
Labels: CSS, React

#225 #221 - Feat: 토큰 검증
  src/App.jsx
  src/pages/Home.jsx
  src/pages/Splash.jsx
Labels: React, API

#227 #226 - 로그아웃 기능 구현
  src/components/common/TopBasicNav.jsx
  src/components/modal/LogoutModal.jsx
  src/components/modal/ProfileModal.jsx
Labels: React, component

#228 Feat/#210/댓글작성시간포맷팅
  src/components/comment/PostComment.jsx
Labels: React, component

#231 #230 - Fix:채팅창 토글이 안닫히는 현상 변경
  src/components/chat/LeaveChatModal.jsx
  src/components/chat/TopChatNav.jsx
Labels: bug

#236 #235 - 앨범형, 리스트형 이미지 svg로 변경
  src/assets/icon/icon-post-album-off.svg
  src/assets/icon/icon-post-album-on.svg
  src/assets/icon/icon-post-list-off.svg
  src/assets/icon/icon-post-list-on.svg
  src/pages/MyProfile.jsx
Labels: CSS

#238 #237 - 팔로우, 팔로잉 리스트 이미지 사이즈 조절
  src/components/follow/FollowerCard.jsx
  src/components/follow/FollowingCard.jsx
  src/pages/style/FollowerList.css
Labels: CSS

#239 #234 - Fix: 채팅, 댓글 말줄임 및 wrap 추가
  src/components/chat/ChatItem.css
  src/components/comment/PostComment.css
Labels: CSS, QA, component

#241 Design/#233/UI수정
  src/components/common/TopMenuComponent.css
  src/components/loginjoin/IdPwForm.css
  src/components/loginjoin/LoginButton.css
  src/components/search/UserList.jsx
  src/pages/EditProfile.jsx
  src/pages/Join.jsx
  src/pages/Login.jsx
  src/pages/SetProfile.jsx
  src/pages/style/EditProfile.css
  src/pages/style/Login.css
  src/pages/style/SetProfile.css
Labels: CSS

#242 #240 - Design: 채팅관련 텍스트 수정
  src/assets/chat-profile.svg
  src/assets/pea-color.svg
  src/assets/salad.avif
  src/components/chat/ChatItem.css
  src/components/chat/TopChatNav.jsx
  src/pages/ChatList.jsx
  src/pages/ChatRoom.jsx
  src/pages/style/ChatRoom.css
Labels: CSS, component

#246 #243 - Fix: 댓글 가림 현상 수정
  src/components/comment/PostCommentInput.css
  src/pages/style/Post.css
Labels: CSS, component

#248 Fix/#244/프로필수정
  src/components/common/BasicProfileImg.css
  src/components/common/BasicProfileImg.jsx
  src/components/profile/ProfileInfo.css
  src/components/profile/ProfileInfo.jsx
Labels: CSS

#250 #245 - Feat: 비밀번호 확인 input 추가
  src/components/loginjoin/IdPwForm.css
  src/pages/Join.jsx
  src/pages/Register.jsx
Labels: React

#254 #253 - Feat:팔로우, 팔로잉 리스트 프로필 소개 말줄임
  src/pages/style/FollowerList.css
Labels: CSS, QA

#256 Fix/#255/팔로우팔로잉리스트limit
  src/pages/FollowerList.jsx
  src/pages/FollowingList.jsx
Labels: CSS, QA

#258 Fix/#257/앨범형리스트형아이콘제거
  src/components/post/PostContainer.jsx
  src/pages/MyProfile.jsx
Labels: CSS, QA

#259 #252 - Fix: 세로 창 축소 시 상단바로 글자 올라오는 현상 해결
  src/pages/Home.jsx
  src/pages/style/Home.css
Labels: bug, CSS, QA

#261 #247 - Feat: 게시글 신고 기능
  src/components/modal/PostAlert.jsx
  src/components/modal/PostModal.jsx
  src/components/post/PostItem.jsx
Labels: React, API

#263 #262 - 유저의 상품 클릭시 404페이지로 이동
  src/App.jsx
  src/components/product/ProductCard.jsx
Labels: QA, component

#265 #264 - 유저프로필에서 프로필버튼 클릭 시 마이페이지로 이동
  src/pages/MyProfile.jsx
Labels: bug, QA

#267 Feat/#266/상품등록inputfocus색변경
  src/pages/UploadProduct.jsx
  src/pages/style/UploadProduct.css
Labels: CSS

#269 #268 - Fix:상품수정 저장 버튼 변경
  src/pages/EditProduct.jsx
Labels: CSS

#270 #260- Feat: 검색결과 클릭 시 해당 프로필로 이동
  src/components/search/UserList.jsx
  src/pages/Search.jsx
Labels: React

#275 #274 - Feat: 로딩 페이지 추가
  src/pages/MyProfile.jsx
  src/pages/NotFound.jsx
  src/pages/Post.jsx
  src/pages/loading.jsx
  src/pages/style/404loading.css
Labels: CSS, React, component

#273 #272 - Feat: 작성자 프로필 이동 기능
  src/components/comment/PostComment.jsx
  src/components/post/PostItem.jsx
Labels: React, QA, component

#278 Feat/#276/팔로잉유저피드뜨게
  src/App.jsx
  src/pages/Home.jsx
  src/pages/style/Home.css
Labels: CSS, React, API

#280 #279 - Feat: 애니메이션 적용
  src/components/loginjoin/LoginButton.css
  src/components/modal/Alert.css
  src/components/modal/Modal.css
Labels: CSS

#282 #281 - Design: 폰트 적용 및 UI 변경
  public/index.html
  src/assets/pea-gray.png
  src/assets/pea-gray2.png
  src/assets/pea-white.png
  src/assets/yeondumarket.png
  src/pages/Splash.jsx
  src/pages/style/404loading.css
  src/pages/style/Home.css
  src/pages/style/Intro.css
  src/pages/style/Splash.css
  src/reset.css
Labels: CSS, React
