Repository Likelion-Project-3/yeondu-market, pull requests merged in 2022-08, with the labels that each got.

#284 #283 - Fix: 프로필 수정 기능 수정
  src/components/profile/ProfileForm.jsx
  src/pages/EditProfile.jsx
Labels: bug, React

#287 #285 - Comment: 아이콘 출처 표기
  src/pages/Home.jsx
  src/pages/Intro.jsx
  src/pages/NotFound.jsx
  src/pages/Splash.jsx
  src/pages/loading.jsx
  src/pages/style/Splash.css
Labels: documentation

#288 #286 - Fix: 모바일 UI 수정
  src/components/chat/ChatItem.css
  src/pages/ChatList.jsx
  src/pages/EditPost.jsx
  src/pages/UploadPost.jsx
  src/pages/style/ChatList.css
  src/pages/style/UploadPost.css
Labels: CSS, React

#290 #229 - Feat:팔로우,팔로잉 리스트 버튼 변화
  src/components/follow/FollowerCard.jsx
  src/components/follow/FollowingCard.jsx
Labels: React, API, component

#293 #292 - 팔로우 팔로잉 리스트에서 tapmenu에 의해 가려지는 내용 수정
  src/pages/style/FollowerList.css
Labels: CSS

#297 Fix/#294/팔로우버튼클릭시재렌더링
  src/components/follow/FollowerCard.jsx
  src/components/follow/FollowerContainer.jsx
  src/pages/FollowerList.jsx
Labels: React, API, component

#299 #289 - Feat: 로딩 컴포넌트
  src/components/common/ContentLoading.css
  src/components/common/ContentLoading.jsx
  src/pages/MyProfile.jsx
  src/pages/PageLoading.jsx
Labels: CSS, React, component

#300 #298 - Fix:유저 프로필 팔로우, 언팔로우 버튼 변화
  src/components/profile/UserProfileBtn.jsx
  src/pages/MyProfile.jsx
Labels: bug, React, API, component

#302 #301 - Fix: 저장버튼 에러 해결 및 콘솔 제거
  src/components/profile/ProfileForm.jsx
  src/pages/EditProfile.jsx
Labels: bug

#308 #307 - Feat : 팔로우, 팔로잉 리스트에서 내프로필 팔로우 버튼 삭제
  src/components/follow/FollowerCard.jsx
  src/components/follow/FollowingCard.jsx
Labels: React, component

#305 Fix/#304/상단검색창고정및디폴트이미지
  src/assets/basic-profile-pea.png
  src/components/common/TopMenuComponent.css
  src/components/common/TopMenuComponent.jsx
  src/components/search/UserList.jsx
  src/pages/Search.jsx
  src/pages/style/Search.css
Labels: bug

#310 #309 - Style: 컴포넌트 재조립
  src/components/button/UploadFileBtn.jsx
  src/components/loginjoin/IdPwForm.jsx
  src/components/loginjoin/LoginButton.jsx
  src/components/profile/ProfileForm.jsx
  src/pages/Join.jsx
  src/pages/Login.jsx
Labels: React, component

#312 Fix/#311/프로필수정및설정수정
  src/components/common/TopMenuComponent.css
  src/pages/EditProfile.jsx
  src/pages/style/SetProfile.css
Labels: React

#314 Design/#313/intro.jsx수정
  src/assets/yeondumarket.png
  src/pages/Intro.jsx
  src/pages/style/Intro.css
  src/pages/style/Splash.css
Labels: CSS

#316 #315 - 팔로우,팔로잉 리스트 헤더 마진 추가
  src/pages/style/FollowerList.css
Labels: CSS

#322 #321 - Chore: 모듈 정리
  src/App.jsx
  src/components/chat/LeaveChatModal.jsx
  src/components/chat/TopChatNav.jsx
  src/components/common/BasicProfileImg.jsx
  src/components/common/TopBasicNav.jsx
  src/components/follow/FollowerCard.jsx
  src/components/follow/FollowerContainer.jsx
  src/components/follow/FollowingCard.jsx
  src/components/modal/ProductAlert.jsx
  src/components/modal/ProductModal.jsx
  src/components/modal/ProfileModal.jsx
  src/components/modal/ReportPostModal.jsx
  src/components/post/Like.jsx
  src/components/post/PostAlbum.jsx
  src/components/post/PostContainer.jsx
  src/components/product/ProductCard.jsx
  src/components/product/ProductContainer.jsx
  src/components/profile/MyProfileBtn.jsx
  src/components/profile/ProfileBtn.jsx
  src/components/profile/ProfileInfo.jsx
  src/pages/ChatList.jsx
  src/pages/EditProduct.jsx
  src/pages/FollowerList.jsx
  src/pages/FollowingList.jsx
  src/pages/Join.jsx
  src/pages/Login.jsx
  src/pages/NotFound.jsx
  src/pages/Profile.jsx
  src/pages/Search.jsx
  src/pages/SetProfile.jsx
  src/pages/Splash.jsx
  src/pages/UploadProduct.jsx
Labels: Chore

#324 #323 - Feat: 유저 컨텍스트 생성
  src/App.jsx
  src/components/comment/PostComment.jsx
  src/components/comment/PostCommentInput.jsx
  src/components/post/PostItem.jsx
  src/context/UserContext.jsx
  src/pages/EditPost.jsx
  src/pages/Post.jsx
  src/pages/UploadPost.jsx
Labels: enhancement, React

#325 #320 - Fix: 상품등록, 수정시 유효성검사 상품명 오류 수정
  src/pages/EditProduct.jsx
  src/pages/UploadProduct.jsx
  src/pages/style/UploadProduct.css
Labels: bug, React

#327 Design/#326/기본프로필이미지변경
  src/assets/basic-profile-img.png
  src/components/chat/ChatItem.css
  src/components/common/BasicProfileImg.jsx
  src/components/profile/ProfileForm.jsx
  src/components/search/UserList.css
  src/components/search/UserList.jsx
  src/pages/style/ChatRoom.css
Labels: CSS, React
